### ISSUE TITLE
Yesterday's cost for account [NOT FOUND]

### ISSUE THREAD

**Issue by colin-l2w** [iandees/aws-billing-to-slack#11]
The issue is that the [Not Found] is caused if the account does not have an alias. 

I'd recommend have it pull the Account number as well as the account alias and if the alias is missing use the account number.

**Comment by Alex-ley** [comment]
@colin-l2w this is fixed in my fork: https://github.com/Alex-ley/aws-billing-to-slack, which I have opened a PR to merge into this repo #16
