### ISSUE TITLE
Got issues when using Server Deploy

### ISSUE THREAD

**Issue by ibitolamayowa** [iandees/aws-billing-to-slack#20]
Error:
Detected unrecognized CLI options: "--slack_url".

I tried deploying but got this error above. Any fix?

**Comment by oluoo** [comment]
Same here, @ibitolamayowa. I was thinking I did something wrong. 

Any fix @iandees?

**Comment by iandees** [comment]
Looks like you're using a more recent version of serverless. I just merged a fix in #19 that should solve it for you.

**Comment by oluoo** [comment]
Thank you.
