### ISSUE TITLE
Security token included in the request is invalid

### ISSUE THREAD

**Issue by oluoo** [iandees/aws-billing-to-slack#21]
I get this error below on deployment

```
× Stack aws-billing-to-slack-prod failed to deploy (31s)
Environment: win32, node 12.13.0, framework 3.8.0, plugin 6.1.6, SDK 4.3.2
Credentials: Local, "default" profile
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
The security token included in the request is invalid.
```

Is this expected?

Any fix @iandees & @dudeitssm

**Comment by iandees** [comment]
That looks like an AWS issue. Look through Google results for that error message.

**Comment by oluoo** [comment]
> That looks like an AWS issue. Look through Google results for that error message.

This was spot on, and thank you for prompt response.
