### ISSUE TITLE
Changing Config to Weekly?

### ISSUE THREAD

**Issue by cricksmaidiene** [iandees/aws-billing-to-slack#32]
Firstly just want to say that this is a pretty seamless app and works great, so thank you for creating it!

Is it possible to have some config that can be changed or a param added (like the slack webhook param) to choose the time interval of the cost data? We're a smaller company so a weekly summary on slack can be pretty useful instead of a daily one which can get a bit spammy in a hurry. Would appreciate your input on this, thanks!

**Comment by iandees** [comment]
You can change the schedule or frequency of posting by changing the cron stanza in the serverless config here: https://github.com/iandees/aws-billing-to-slack/blob/cf9319ea801d20082321fdc87fbd4577a01c5e16/serverless.yml#L39-L41

You can use a website like https://crontab.guru/ to build the string that goes in there.
