### ISSUE TITLE
Error when running on lambda

### ISSUE THREAD

**Issue by anphn** [iandees/aws-billing-to-slack#42]
I have successfully deployed the application, but I get an error when I run it
{
  "errorMessage": "Unable to import module 'handler': libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "07d1e5b6-4afe-41da-84e7-e9c44d91be4f",
  "stackTrace": []
}
Anyone know how to fix it please help me.

**Comment by iandees** [comment]
Can you describe how you deployed it? Did you follow the readme instructions? Did it always fail this way?

**Comment by anphn** [comment]
I installed according to the readme instructions. I changed the runtime in lambda to python3.9 and it worked.

**Comment by anphn** [comment]
let me ask more, i received bill to slack, but today is 12th but bill result is 10th. is that correct?
