### ISSUE TITLE
There is a logic problem with the code.

### ISSUE THREAD

**Issue by binnythomas-1989** [iandees/aws-billing-to-slack#5]
Some of the service cost comes with blank spaces so when you use that for the spark lines it would give wrong results. Re-using this code is a pain. I have been trying to work out to the blanks to 0 so we could aggregate the cost.
![Screenshot 2020-08-15 at 22 01 35](https://user-images.githubusercontent.com/58479634/90329801-99b82e00-df9f-11ea-98a2-cf2f8b84d690.png)

**Comment by Alex-ley** [comment]
@binnythomas-1989 this is fixed in my fork: https://github.com/Alex-ley/aws-billing-to-slack, which I have opened a PR to merge into this repo #16
