### ISSUE TITLE
How do I debug slight discrepancies in cost?

### ISSUE THREAD

**Issue by GlacierWalrus** [iandees/aws-billing-to-slack#52]
Thank you for the plugin, it's very helpful.

I've been running it for about 3 weeks and I've noticed a slight difference in the slack reported costs compared to was AWS Cost explorer reports.

Please see the following example. The slack report on the 6th of April for the 5th of April reports EC2 and ELB costs slightly lower than what cost explorer reports for the 5th April.

<img width="1416" alt="image" src="https://github.com/iandees/aws-billing-to-slack/assets/114941647/b6d52488-b2b2-4db7-8c3d-e86f7274f03a">

You can also see that there's a similar issue for the day before.
<img width="1425" alt="image" src="https://github.com/iandees/aws-billing-to-slack/assets/114941647/8c506b40-7786-4280-ae32-851a5d4db8d0">

I thought perhaps there was a permission issue, but there are no errors in the lambda log.

Do you have any suggestions about what might be going wrong?

**Comment by iandees** [comment]
A couple ideas:
* AWS cost reports are constantly changing until they send the bill for that month out. The dates with asterisks next to them in the cost explorer are still provisional and subject to change. This is the same data that the Slack bot uses, so depending on when the slack bot ran and posted its message, it might get different data than what you're seeing in the cost explorer graph. To debug this, you could check the cost dashboard very close to the same time your slack bot posts to see if the data lines up.
* The Slack bot code might be off by one on dates when it calculates "yesterday". A trace through the code to confirm what dates its using would be the best way to debug this.

**Comment by GlacierWalrus** [comment]
I think your first point is correct in this case, I'm closing my investigation, thank you for your help.

For the record, here is the cost explorer breakdown sampled a few minutes after the slack message
<img width="1547" alt="Screenshot 2024-04-11 at 16 06 13" src="https://github.com/iandees/aws-billing-to-slack/assets/114941647/97f9fa29-7b45-4c85-916a-a2e3fd5da693">

Here is the cost explorer breakdown 21 hours later
![image](https://github.com/iandees/aws-billing-to-slack/assets/114941647/69cd8551-ba6c-499a-ae45-748aeb586eb4)

**Comment by iandees** [comment]
Great, thanks for looking into it and sharing the results. I didn't expect the cost info to change that quickly.
