### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by colin-l2w** [iandees/aws-billing-to-slack#9]
The example doesn't work or provide much information.

There is a bit of setup with serverless to create a directory. And the service does not run with invoke function. Also the function does not show in the list.
`serverless deploy list functions
Serverless: Listing functions and their last 5 versions:
Serverless: -------------
Serverless: hello: $LATEST, 1, 2`

**Comment by iandees** [comment]
I just went through the documentation from a fresh install and it worked for me. Can you paste any error or stack traces you get?

**Comment by colin-l2w** [comment]
The issue is that there are missing steps:


Also installing NPM and changing the python version from 3.7 to 3.8. The python version should be >= 3.7 not == 3.7. 
I had to install pylint on my system as well.

Steps:

0. Create a directory and clone the repository
1. Install Python requirements 
2. Install pipenv 
3. sls plugin install -n serverless-python-requirements
4. Create the service
	serverless create --template-url="https://github.com/iandees/aws-billing-to-slack.git" \ --path="app-aws-cost" \ --name="app-aws-cost"
5. Deploy the service
	serverless deploy --stage="prod" --verbose --slack_url="https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxx"

	
I am also getting this message:
"Yesterday's cost for account [NOT FOUND] was"

**Comment by colin-l2w** [comment]
I forked the repository and created a pull request to update the readMe. if I have time, I'll fix the Lambda function for the not found later this week.
